# Generated by Django 3.0.4 on 2021-02-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorUsername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoseURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseURL', models.CharField(max_length=20)),
                ('prescriptionID', models.CharField(max_length=50)),
                ('doseNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosageForm', models.CharField(max_length=50)),
                ('doseValue', models.IntegerField()),
                ('doseUnit', models.CharField(max_length=10)),
                ('drug', models.CharField(max_length=50)),
                ('durationValue', models.IntegerField()),
                ('durationUnit', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication1Code', models.CharField(max_length=20)),
                ('medication2Code', models.CharField(max_length=20)),
                ('conflictDetails', models.CharField(max_length=700)),
                ('conflictSeverity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationCode', models.CharField(max_length=20)),
                ('medicationName', models.CharField(max_length=50)),
                ('medicationNotes', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientUsername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacistUsername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('dateDispensed', models.CharField(max_length=50)),
                ('dateIssued', models.CharField(max_length=50)),
                ('dataReceived', models.CharField(max_length=50)),
                ('dispensed', models.BooleanField()),
                ('doctorId', models.CharField(max_length=50)),
                ('patientId', models.CharField(max_length=50)),
                ('pharmacyId', models.CharField(max_length=50)),
                ('pharmacyNote', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugTracker.Item')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrugTracker.Prescription')),
            ],
        ),
    ]
