# Generated by Django 3.0.4 on 2021-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationCode', models.CharField(max_length=50)),
                ('medicationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('medicationCode', models.CharField(max_length=50)),
                ('medicationDose', models.CharField(max_length=50)),
                ('timesPerday', models.IntegerField()),
                ('IntervalBetweenDoses', models.IntegerField()),
                ('perscriptionStartDate', models.DateField()),
                ('totalNumberOfDoses', models.IntegerField()),
            ],
        ),
    ]
