# Generated by Django 3.0.4 on 2021-02-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dataReceived',
            new_name='dateReceived',
        ),
    ]
