# Generated by Django 3.0.4 on 2021-02-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perscription',
            old_name='IntervalBetweenDoses',
            new_name='intervalBetweenDoses',
        ),
        migrations.RenameField(
            model_name='perscription',
            old_name='timesPerday',
            new_name='timesPerDay',
        ),
    ]
