# Generated by Django 3.0.4 on 2021-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0002_drugconflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=5000)),
            ],
        ),
    ]
