# Generated by Django 3.0.4 on 2021-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0002_auto_20210203_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='perscription',
            name='doseUnit',
            field=models.CharField(default='mg', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perscription',
            name='medicationCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perscription',
            name='medicationDose',
            field=models.IntegerField(),
        ),
    ]
