# Generated by Django 3.0.4 on 2021-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0003_drugnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorUsername', models.CharField(max_length=50)),
                ('patientUsername', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='startDate',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
