# Generated by Django 3.0.4 on 2021-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0003_auto_20210206_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseURL', models.CharField(max_length=20)),
                ('perscriptionID', models.CharField(max_length=50)),
                ('doseNumber', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='perscription',
            name='perscriptionID',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
