# Generated by Django 3.0.4 on 2021-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0004_auto_20210206_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication1Code', models.CharField(max_length=20)),
                ('medication2Code', models.CharField(max_length=20)),
            ],
        ),
    ]
