# Generated by Django 3.0.4 on 2021-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0004_auto_20210223_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='videoRequired',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
