# Generated by Django 3.0.4 on 2021-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0005_item_videorequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='videoURL',
            field=models.CharField(default='12345678910', max_length=10),
            preserve_default=False,
        ),
    ]
