# Generated by Django 3.0.4 on 2021-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0007_auto_20210217_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='medconflict',
            name='conflictSeverity',
            field=models.CharField(default='SEVERE', max_length=20),
            preserve_default=False,
        ),
    ]
