# Generated by Django 3.0.4 on 2021-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0010_auto_20210304_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dateDispensed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dateReceived',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacyNote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
