# Generated by Django 3.0.4 on 2021-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0013_prescriptioncollector'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientUsername', models.CharField(max_length=50)),
                ('pharmacyId', models.CharField(max_length=50)),
            ],
        ),
    ]
