# Generated by Django 3.0.4 on 2021-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugTracker', '0015_patientgms'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConfidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseURL', models.CharField(max_length=10)),
                ('uploadDate', models.DateTimeField()),
                ('confidenceScore', models.IntegerField()),
            ],
        ),
    ]
